<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import { ChevronLeft, ChevronRight } from 'lucide-svelte'

  import { COURSE_PROSE_CLASS } from '$lib/constants/styles'

  let { data } = $props()
  // data.chapter -> { title, content, html, ... }
  // data.pagination -> { prev, next }
</script>

<article class={COURSE_PROSE_CLASS}>
  <h1 class="text-4xl">{data.chapter.title}</h1>

  <!-- Render HTML content generated by marked -->
  {@html data.chapter.html}
</article>

<div class="mt-20 flex items-center justify-between border-t border-gray-100 pt-8">
  <!-- Prev Button -->
  <div>
    {#if data.pagination.prev}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-start gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.prev.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          <ChevronLeft class="mr-1 h-3 w-3" /> Previous
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.prev.title}</span>
      </Button>
    {/if}
  </div>

  <!-- Next Button -->
  <div>
    {#if data.pagination.next}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-end gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.next.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          Next <ChevronRight class="ml-1 h-3 w-3" />
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.next.title}</span>
      </Button>
    {/if}
  </div>
</div>

<style>
  /* Table Styling to match TiptapEditor */
  :global(article table) {
    border-collapse: separate;
    border-spacing: 0;
    margin-top: 2em;
    margin-bottom: 2em;
    overflow: hidden;
    table-layout: fixed;
    width: 100%;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
  }
  :global(article td),
  :global(article th) {
    box-sizing: border-box;
    min-width: 1em;
    padding: 6px 8px;
    position: relative;
    vertical-align: top;
    border-right: 1px solid #e5e7eb;
    border-bottom: 1px solid #e5e7eb;
  }
  /* Remove right border from last column */
  :global(article td:last-child),
  :global(article th:last-child) {
    border-right: none;
  }
  /* Remove bottom border from last row cells */
  :global(article tr:last-child td) {
    border-bottom: none;
  }

  :global(article th) {
    font-weight: 600;
    text-align: left;
  }

  /* Shared Media Styles for consistency */
  :global(article img) {
    max-width: 100%;
    height: auto;
    margin: 1.5rem auto;
    display: block;
    border-radius: 0.5rem;
    box-shadow:
      0 1px 3px 0 rgb(0 0 0 / 0.1),
      0 1px 2px -1px rgb(0 0 0 / 0.1);
  }
  :global(article .iframe-wrapper) {
    width: 100%;
    margin: 1.5rem 0;
    display: flex;
    justify-content: center;
  }
  :global(article iframe) {
    width: 100%;
    aspect-ratio: 16/9;
    margin: 0 auto;
    border-radius: 0.5rem;
  }

  /* Task List Styles (Matching Editor) */
  :global(article ul[data-type='taskList']) {
    list-style: none;
    padding: 0;
    margin: 1rem 0;
  }
  :global(article li[data-type='taskItem']) {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin: 0.25rem 0;
  }
  /* Remove prose markers */
  :global(article li[data-type='taskItem']::before),
  :global(article li[data-type='taskItem']::marker) {
    content: none !important;
    display: none;
  }

  :global(article li[data-type='taskItem'] label) {
    margin: 0;
    user-select: none;
  }

  :global(article li[data-type='taskItem'] input) {
    appearance: none;
    -webkit-appearance: none;
    background-color: transparent;
    cursor: pointer;
    width: 1.15rem;
    height: 1.15rem;
    border: 1.5px solid #d1d5db;
    border-radius: 0.35rem;
    transition: all 0.2s ease;
    display: grid;
    place-content: center;
    margin: 0;
  }

  :global(article li[data-type='taskItem'] input:checked) {
    background-color: #000;
    border-color: #000;
  }

  :global(article li[data-type='taskItem'] input::before) {
    content: '';
    width: 0.65rem;
    height: 0.65rem;
    background-color: white;
    transform: scale(0);
    transition: transform 0.1s ease-in-out;
    mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='4' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='20 6 9 17 4 12'%3E%3C/polyline%3E%3C/svg%3E");
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='4' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='20 6 9 17 4 12'%3E%3C/polyline%3E%3C/svg%3E");
    mask-size: contain;
    -webkit-mask-size: contain;
    mask-repeat: no-repeat;
    -webkit-mask-repeat: no-repeat;
    mask-position: center;
    -webkit-mask-position: center;
  }

  :global(article li[data-type='taskItem'] input:checked::before) {
    transform: scale(1);
  }

  :global(article li[data-type='taskItem'][data-checked='true'] > div) {
    text-decoration: line-through;
    color: #9ca3af;
    opacity: 0.8;
  }
</style>
