<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import { ChevronLeft, ChevronRight } from 'lucide-svelte'

  import { COURSE_PROSE_CLASS } from '$lib/constants/styles'

  let { data } = $props()
  // data.chapter -> { title, content, html, ... }
  // data.pagination -> { prev, next }
</script>

<article class={COURSE_PROSE_CLASS}>
  <h1 class="text-4xl">{data.chapter.title}</h1>

  <!-- Render HTML content generated by marked -->
  {@html data.chapter.html}
</article>

<div class="mt-20 flex items-center justify-between border-t border-gray-100 pt-8">
  <!-- Prev Button -->
  <div>
    {#if data.pagination.prev}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-start gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.prev.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          <ChevronLeft class="mr-1 h-3 w-3" /> Previous
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.prev.title}</span>
      </Button>
    {/if}
  </div>

  <!-- Next Button -->
  <div>
    {#if data.pagination.next}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-end gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.next.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          Next <ChevronRight class="ml-1 h-3 w-3" />
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.next.title}</span>
      </Button>
    {/if}
  </div>
</div>

<style>
  /* Table Styling to match TiptapEditor */
  :global(article table) {
    border-collapse: separate;
    border-spacing: 0;
    margin-top: 2em;
    margin-bottom: 2em;
    overflow: hidden;
    table-layout: fixed;
    width: 100%;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
  }
  :global(article td),
  :global(article th) {
    box-sizing: border-box;
    min-width: 1em;
    padding: 6px 8px;
    position: relative;
    vertical-align: top;
    border-right: 1px solid #e5e7eb;
    border-bottom: 1px solid #e5e7eb;
  }
  /* Remove right border from last column */
  :global(article td:last-child),
  :global(article th:last-child) {
    border-right: none;
  }
  /* Remove bottom border from last row cells */
  :global(article tr:last-child td) {
    border-bottom: none;
  }

  :global(article th) {
    font-weight: 600;
    text-align: left;
  }

  /* Shared Media Styles for consistency */
  :global(article img) {
    max-width: 100%;
    height: auto;
    margin: 1.5rem auto;
    display: block;
    border-radius: 0.5rem;
    box-shadow:
      0 1px 3px 0 rgb(0 0 0 / 0.1),
      0 1px 2px -1px rgb(0 0 0 / 0.1);
  }
  :global(article .iframe-wrapper) {
    width: 100%;
    margin: 1.5rem 0;
    display: flex;
    justify-content: center;
  }
  :global(article iframe) {
    max-width: 100%;
    margin: 0 auto;
    border-radius: 0.5rem;
  }
</style>
