<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import { ChevronLeft, ChevronRight } from 'lucide-svelte'

  let { data } = $props()
  // data.chapter -> { title, content, html, ... }
  // data.pagination -> { prev, next }
</script>

<article
  class="prose prose-slate prose-lg prose-headings:font-bold
    prose-headings:tracking-tight prose-headings:text-gray-900 prose-p:text-gray-600
    prose-p:leading-7 prose-a:text-violet-600
    prose-a:no-underline hover:prose-a:underline prose-pre:bg-gray-50
    prose-pre:border prose-pre:text-gray-900 max-w-none"
>
  <h1 class="text-4xl">{data.chapter.title}</h1>

  <!-- Render HTML content generated by marked -->
  {@html data.chapter.html}
</article>

<div class="mt-20 flex items-center justify-between border-t border-gray-100 pt-8">
  <!-- Prev Button -->
  <div>
    {#if data.pagination.prev}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-start gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.prev.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          <ChevronLeft class="mr-1 h-3 w-3" /> Previous
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.prev.title}</span>
      </Button>
    {/if}
  </div>

  <!-- Next Button -->
  <div>
    {#if data.pagination.next}
      <Button
        variant="outline"
        class="group flex h-auto flex-col items-end gap-1 px-4 py-3 transition-all hover:border-violet-300 hover:bg-violet-50"
        href="/learn/course/{data.course.slug}/{data.pagination.next.slug}"
      >
        <span class="flex items-center text-xs font-medium text-gray-400 group-hover:text-violet-600">
          Next <ChevronRight class="ml-1 h-3 w-3" />
        </span>
        <span class="text-sm font-semibold text-gray-700 group-hover:text-violet-900">{data.pagination.next.title}</span>
      </Button>
    {/if}
  </div>
</div>
